### ISSUE TITLE
Exception in GarbageCleaner

### ISSUE THREAD

**Issue by geoff-addepar** [geoff-addepar/heap-dump#1]
```
./ParseHeapDump.sh /home/geoff/heap_dumps/core/cmd_heap.bin org.eclipse.mat.api:suspects org.eclipse.mat.api:top_components
```

results in

```
java.lang.NullPointerException
    at org.eclipse.mat.parser.internal.GarbageCleaner.createHistogramOfUnreachableObjects(GarbageCleaner.java:544)
    at org.eclipse.mat.parser.internal.GarbageCleaner.clean(GarbageCleaner.java:125)
    at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.parse(SnapshotFactoryImpl.java:231)
    at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.openSnapshot(SnapshotFactoryImpl.java:126)
    at org.eclipse.mat.snapshot.SnapshotFactory.openSnapshot(SnapshotFactory.java:145)
    at org.eclipse.mat.internal.apps.ParseSnapshotApp.parse(ParseSnapshotApp.java:134)
    at org.eclipse.mat.internal.apps.ParseSnapshotApp.start(ParseSnapshotApp.java:106)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by geoff-addepar** [comment]
Fixed in 0.2

**Comment by tekknolagi** [comment]
I am seeing this issue in Eclipse Memory Analyzer Version 1.9.2. What commit fixed it? What is the best way to build MAT and debug further? Cheers.

**Comment by tekknolagi** [comment]
Oh you know what, I'm sorry. This is not a repo for MAT. My apologies. I would be curious to know, though, what bug you had that caused this.

**Comment by glywood** [comment]
This was well over 3 years ago, and I can't recall exactly, but it looks like commit 7fa5bcd3f46c83af970f4620774779a6b18dcc47 (in my repo) fixed it.

It was a bug in the way heap dumps were generated, and my tool was creating heap dumps that had inconsistent metadata about what classes exist (probably duplicate classes). I doubt the exact same thing is happening again.

The only other thing I can really point you at is the source, which is here: https://git.eclipse.org/c/mat/org.eclipse.mat.git/tree/plugins/org.eclipse.mat.parser/src/org/eclipse/mat/parser/internal/GarbageCleaner.java?h=1.9.x
