### ISSUE TITLE
Performance issues when using CMS

### ISSUE THREAD

**Issue by geoff-addepar** [geoff-addepar/heap-dump#2]
It gets stuck finding live regions, before it even starts walking the heap at all:

```
    at sun.jvm.hotspot.runtime.VirtualBaseConstructor.instantiateWrapperFor(VirtualBaseConstructor.java:104)
    at sun.jvm.hotspot.oops.Metadata.instantiateWrapperFor(Metadata.java:68)
    at sun.jvm.hotspot.oops.Oop.getKlassForOopHandle(Oop.java:213)
    at sun.jvm.hotspot.oops.ObjectHeap.newOop(ObjectHeap.java:251)
    at sun.jvm.hotspot.memory.CompactibleFreeListSpace.getLiveRegions(CompactibleFreeListSpace.java:189)
    at sun.jvm.hotspot.oops.ObjectHeap$LiveRegionsCollector.doSpace(ObjectHeap.java:401)
    at sun.jvm.hotspot.memory.ConcurrentMarkSweepGeneration.spaceIterate(ConcurrentMarkSweepGeneration.java:66)
    at sun.jvm.hotspot.oops.ObjectHeap.collectLiveRegions(ObjectHeap.java:426)
    at sun.jvm.hotspot.oops.ObjectHeap.iterate(ObjectHeap.java:171)
    at com.addepar.heapdump.HeapHprofBinWriter.writeClasses(HeapHprofBinWriter.java:1089)
```

**Comment by geoff-addepar** [comment]
Fixed on v0.3
