### ISSUE TITLE
UnalignedAddressException while trying to parse a core from gdb

### ISSUE THREAD

**Issue by AdallomRoy** [geoff-addepar/heap-dump#3]
```
Attaching to core core-problem.core from executable /usr/bin/java, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.60-b23
Dumping heap to core.hprof ...
Exception in thread "main" sun.jvm.hotspot.debugger.UnalignedAddressException: 8cca638f3
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1.checkAlignment(LinuxDebuggerLocal.java:192)
        at sun.jvm.hotspot.debugger.DebuggerBase.readJInt(DebuggerBase.java:315)
        at sun.jvm.hotspot.debugger.linux.LinuxAddress.getJIntAt(LinuxAddress.java:112)
        at com.addepar.heapdump.FastObjectHeap.newOop(FastObjectHeap.java:75)
        at sun.jvm.hotspot.classfile.ClassLoaderData.getClassLoader(ClassLoaderData.java:64)
        at sun.jvm.hotspot.memory.DictionaryEntry.loader(DictionaryEntry.java:63)
        at sun.jvm.hotspot.memory.Dictionary.classesDo(Dictionary.java:67)
        at sun.jvm.hotspot.memory.SystemDictionary.classesDo(SystemDictionary.java:190)
        at sun.jvm.hotspot.memory.SystemDictionary.allClassesDo(SystemDictionary.java:183)
        at com.addepar.heapdump.HeapHprofBinWriter.writeClasses(HeapHprofBinWriter.java:1089)
        at com.addepar.heapdump.HeapHprofBinWriter.write(HeapHprofBinWriter.java:485)
        at com.addepar.heapdump.HeapDumper.run(HeapDumper.java:57)
        at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at com.addepar.heapdump.HeapDumper.main(HeapDumper.java:78)

```

**Comment by geoff-addepar** [comment]
Any chance I can take a look at the core file? If it contains sensitive information and you can't give it to me, that's ok.

If the core file was taken while the JVM was compacting the heap, it's possible the tool won't be able to recover anything. In the best case it could fail with a more reasonable error message.

**Comment by geoff-addepar** [comment]
One more thing I thought of: can you also provide the command line you used to start the JVM? I'd like to know which GC was in use, and whether or not compressed OOPs are enabled. (This is also available in the core file, but there's less danger of sensitive information on the command line)

**Comment by AdallomRoy** [comment]
These are the parameters:

/usr/bin/java -server -Djava.net.preferIPv4Stack=true -Des.config=/usr/local/etc/elasticsearch/elasticsearch.yml -Xms30g -Xmx30g -Xss256k -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Delasticsearch -Des.pidfile=/usr/local/var/run/elasticsearch/XXX.pid -Des.foreground=yes -Des.path.home=/usr/local/elasticsearch -cp :/usr/local/elasticsearch/lib/_:/usr/local/elasticsearch/lib/sigar/_ org.elasticsearch.bootstrap.Elasticsearch

The dump is both sensitive and very (very) large :)

**Comment by geoff-addepar** [comment]
It looks like you most likely dumped the JVM while it was compacting, and the tool is running into a free memory chunk where it expected an object. I will try to write some code to handle in-progress garbage collection a little better. Be warned that it might take some time for me to make any changes; this is a side project and I don't know when I'll be able to get to it.

In the meantime, I would suggest using

```
jmap -J-Dsun.tools.attach.attachTimeout=120000 -dump:format=b,file=<file> <pid>
```

which will allow more time for a regular jmap to succeed. Compacting a large heap like yours can take a long time, and the default timeout of 5 seconds often isn't long enough.

**Comment by mehuljain53** [comment]
Do we have a fix for this issue?
Running into the same issue:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.UnalignedAddressException: 7e0800001
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1.checkAlignment(LinuxDebuggerLocal.java:192)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.readCInteger(LinuxDebuggerLocal.java:494)
	at sun.jvm.hotspot.debugger.DebuggerBase.readAddressValue(DebuggerBase.java:462)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.readAddress(LinuxDebuggerLocal.java:433)
	at sun.jvm.hotspot.debugger.linux.LinuxAddress.getAddressAt(LinuxAddress.java:74)
	at sun.jvm.hotspot.types.basic.BasicTypeDataBase.findDynamicTypeForAddress(BasicTypeDataBase.java:296)
	at sun.jvm.hotspot.runtime.VirtualBaseConstructor.instantiateWrapperFor(VirtualBaseConstructor.java:102)
	at sun.jvm.hotspot.oops.Metadata.instantiateWrapperFor(Metadata.java:68)
	at sun.jvm.hotspot.oops.Oop.getKlassForOopHandle(Oop.java:211)
	at sun.jvm.hotspot.oops.ObjectHeap.newOop(ObjectHeap.java:251)
	at sun.jvm.hotspot.classfile.ClassLoaderData.getClassLoader(ClassLoaderData.java:64)
	at sun.jvm.hotspot.memory.DictionaryEntry.loader(DictionaryEntry.java:63)
	at sun.jvm.hotspot.memory.Dictionary.classesDo(Dictionary.java:67)
	at sun.jvm.hotspot.memory.SystemDictionary.classesDo(SystemDictionary.java:190)
	at sun.jvm.hotspot.memory.SystemDictionary.allClassesDo(SystemDictionary.java:183)
	at sun.jvm.hotspot.utilities.HeapHprofBinWriter.writeClasses(HeapHprofBinWriter.java:954)
	at sun.jvm.hotspot.utilities.HeapHprofBinWriter.write(HeapHprofBinWriter.java:427)
	at sun.jvm.hotspot.tools.HeapDumper.run(HeapDumper.java:62)
	at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.HeapDumper.main(HeapDumper.java:83)

**Comment by glywood** [comment]
No fix available, and it's unlikely I will make one at this point. Also, that stack trace doesn't include any code from this github project; if this is a bug with the JVM tools you should report it directly against them.
